# Generated by Django 4.2.5 on 2023-09-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='default_picture.png', upload_to='users_profile/'),
        ),
    ]
