# Generated by Django 4.0 on 2023-10-05 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookauthor',
            name='user',
        ),
    ]
