# Generated by Django 4.0 on 2023-10-15 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('books', '0007_reviewlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlikes',
            name='likers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
    ]
