# Generated by Django 4.0 on 2023-10-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_delete_reviewlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestauthoruser',
            name='is_status',
        ),
    ]
